### ISSUE TITLE
Dismiss problem with iOs 7.1 beta 5 

### ISSUE THREAD

**Issue by ZoeVale** [Dimillian/DMCustomTransitions#2]
Hi, i love your framework but i notice few error with iOs 7.1 bets 5.
Sometimes mistakes at the start of transition, sometimes to dismiss. 
Thanks for all.

**Comment by Dimillian** [comment]
Crash ?

**Comment by ZoeVale** [comment]
Yes!

**Comment by Dimillian** [comment]
Fixed!

**Comment by ZoeVale** [comment]
Thanks for all.
Very fast!!! ;-)
